github.com:
    users:
        GuiCavalcanteDev:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: GuiCavalcanteDev
